{
  config,
  lib,
  pkgs,
  ...
}: let
  inherit (lib)
    concatMapStringsSep
    concatStringsSep
    getExe
    isBool
    isInt
    isList
    isString
    mapAttrsToList
    mkDefault
    mkEnableOption
    mkIf
    mkOption
    mkPackageOption
    types
    ;

  cfg = config.services.owntone;

  # Type for values within a libconfuse section:
  # bool, int, string, or list-of-string.
  sectionValueType = types.oneOf [
    types.bool
    types.int
    types.str
    (types.listOf types.str)
  ];

  # Serialize a single value to libconfuse syntax.
  formatValue = v:
    if isBool v
    then
      (
        if v
        then "true"
        else "false"
      )
    else if isInt v
    then toString v
    else if isString v
    then ''"${v}"''
    else if isList v
    then "{ ${concatMapStringsSep ", " (x: ''"${x}"'') v} }"
    else throw "owntone: unsupported config value type";

  # Serialize settings attrset to owntone.conf (libconfuse format).
  # Structure: { section = { key = value; ... }; ... }
  toLibConfuse = settings:
    concatStringsSep "\n\n" (mapAttrsToList (
        section: values:
          "${section} {\n${
            concatStringsSep "\n" (mapAttrsToList (
                key: value: "\t${key} = ${formatValue value}"
              )
              values)
          }\n}"
      )
      settings);

  configFile = pkgs.writeText "owntone.conf" ''
    # Generated by NixOS
    ${toLibConfuse cfg.settings}

    ${cfg.extraConfig}
  '';
in {
  options.services.owntone = {
    enable = mkEnableOption "OwnTone media server (AirPlay/DAAP)";

    package = mkPackageOption pkgs "owntone" {};

    user = mkOption {
      type = types.str;
      default = "owntone";
      description = "User account under which OwnTone runs.";
    };

    group = mkOption {
      type = types.str;
      default = "owntone";
      description = "Group under which OwnTone runs.";
    };

    dataDir = mkOption {
      type = types.path;
      default = "/var/lib/owntone";
      description = "Directory for OwnTone state (database, cache).";
    };

    openFirewall = mkOption {
      type = types.bool;
      default = false;
      description = "Whether to open firewall ports for OwnTone (DAAP + mDNS).";
    };

    settings = mkOption {
      type = types.attrsOf (types.attrsOf sectionValueType);
      default = {};
      description = ''
        OwnTone configuration as a Nix attribute set.
        Top-level keys are section names (general, library, audio, etc.).
        Values within sections can be booleans, integers, strings,
        or lists of strings.

        See <https://github.com/owntone/owntone-server/blob/master/owntone.conf.in>
        for all available options.
      '';
    };

    extraConfig = mkOption {
      type = types.lines;
      default = "";
      description = ''
        Extra lines appended verbatim to owntone.conf.
        Useful for named device sections that cannot be expressed
        as attribute sets, e.g.:

            airplay "Living Room HomePod" {
              max_volume = 11
            }
      '';
    };
  };

  config = mkIf cfg.enable {
    # Sensible defaults; host configs can override via normal priority.
    services.owntone.settings = {
      general = {
        uid = mkDefault cfg.user;
        db_path = mkDefault "${cfg.dataDir}/songs3.db";
        cache_dir = mkDefault "${cfg.dataDir}/cache";
        logfile = mkDefault "/var/log/owntone.log";
        loglevel = mkDefault "log";
      };
      library = {
        name = mkDefault "OwnTone on %h";
        port = mkDefault 3689;
      };
    };

    users.users = mkIf (cfg.user == "owntone") {
      owntone = {
        isSystemUser = true;
        group = cfg.group;
        home = cfg.dataDir;
        extraGroups = ["audio"];
      };
    };

    users.groups = mkIf (cfg.group == "owntone") {
      owntone = {};
    };

    systemd.tmpfiles.rules = [
      "d ${cfg.dataDir} 0755 ${cfg.user} ${cfg.group} -"
      "d ${cfg.dataDir}/cache 0755 ${cfg.user} ${cfg.group} -"
      "f /var/log/owntone.log 0644 ${cfg.user} ${cfg.group} -"
    ];

    systemd.services.owntone = {
      description = "OwnTone DAAP/AirPlay media server";
      after = ["network-online.target" "avahi-daemon.socket"];
      requires = ["network.target" "local-fs.target" "avahi-daemon.socket"];
      wants = ["network-online.target"];
      wantedBy = ["multi-user.target"];

      restartTriggers = [configFile];

      startLimitBurst = 10;
      startLimitIntervalSec = 600;

      serviceConfig = {
        Type = "simple";
        ExecStart = "${getExe cfg.package} -f -c ${configFile}";
        User = cfg.user;
        Group = cfg.group;

        # Resource limits (from upstream systemd unit)
        MemoryMax = "256M";
        MemorySwapMax = "32M";

        # Restart policy
        Restart = "on-failure";
        RestartSec = 5;

        # Hardening
        NoNewPrivileges = true;
        ProtectSystem = "strict";
        ProtectHome = true;
        PrivateTmp = true;
        ReadWritePaths = [
          cfg.dataDir
          "/var/log"
        ];
      };
    };

    networking.firewall = mkIf cfg.openFirewall {
      allowedTCPPorts = [cfg.settings.library.port];
      allowedUDPPorts = [5353];
    };
  };
}
