{
  config,
  lib,
  pkgs,
  ...
}: let
  inherit (lib)
    concatMapStringsSep
    concatStringsSep
    getExe
    isBool
    isInt
    isList
    isString
    mapAttrsToList
    mkDefault
    mkEnableOption
    mkIf
    mkMerge
    mkOption
    mkPackageOption
    types
    ;

  cfg = config.services.owntone;
  ccfg = cfg.controller;

  controllerFormat = pkgs.formats.json {};

  # Type for values within a libconfuse section:
  # bool, int, string, or list-of-string.
  sectionValueType = types.oneOf [
    types.bool
    types.int
    types.str
    (types.listOf types.str)
  ];

  # Serialize a single value to libconfuse syntax.
  formatValue = v:
    if isBool v
    then
      (
        if v
        then "true"
        else "false"
      )
    else if isInt v
    then toString v
    else if isString v
    then ''"${v}"''
    else if isList v
    then "{ ${concatMapStringsSep ", " (x: ''"${x}"'') v} }"
    else throw "owntone: unsupported config value type";

  # Serialize settings attrset to owntone.conf (libconfuse format).
  # Structure: { section = { key = value; ... }; ... }
  toLibConfuse = settings:
    concatStringsSep "\n\n" (mapAttrsToList (
        section: values:
          "${section} {\n${
            concatStringsSep "\n" (mapAttrsToList (
                key: value: "\t${key} = ${formatValue value}"
              )
              values)
          }\n}"
      )
      settings);

  configFile = pkgs.writeText "owntone.conf" ''
    # Generated by NixOS
    ${toLibConfuse cfg.settings}

    ${cfg.extraConfig}
  '';
in {
  options.services.owntone = {
    enable = mkEnableOption "OwnTone media server (AirPlay/DAAP)";

    package = mkPackageOption pkgs "owntone" {};

    user = mkOption {
      type = types.str;
      default = "owntone";
      description = "User account under which OwnTone runs.";
    };

    group = mkOption {
      type = types.str;
      default = "owntone";
      description = "Group under which OwnTone runs.";
    };

    dataDir = mkOption {
      type = types.path;
      default = "/var/lib/owntone";
      description = "Directory for OwnTone state (database, cache).";
    };

    openFirewall = mkOption {
      type = types.bool;
      default = false;
      description = "Whether to open firewall ports for OwnTone (DAAP + mDNS).";
    };

    settings = mkOption {
      type = types.attrsOf (types.attrsOf sectionValueType);
      default = {};
      description = ''
        OwnTone configuration as a Nix attribute set.
        Top-level keys are section names (general, library, audio, etc.).
        Values within sections can be booleans, integers, strings,
        or lists of strings.

        See <https://github.com/owntone/owntone-server/blob/master/owntone.conf.in>
        for all available options.
      '';
    };

    extraConfig = mkOption {
      type = types.lines;
      default = "";
      description = ''
        Extra lines appended verbatim to owntone.conf.
        Useful for named device sections that cannot be expressed
        as attribute sets, e.g.:

            airplay "Living Room HomePod" {
              max_volume = 11
            }
      '';
    };

    controller = {
      enable = mkEnableOption "p3-controller HTTP API for scheduled OwnTone playback";

      package = mkPackageOption pkgs "p3-controller" {};

      port = mkOption {
        type = types.port;
        default = 8085;
        description = "Port for the p3-controller HTTP server.";
      };

      openFirewall = mkOption {
        type = types.bool;
        default = false;
        description = "Whether to open the firewall for the controller port.";
      };

      settings = mkOption {
        type = controllerFormat.type;
        default = {};
        description = ''
          p3-controller configuration. Serialized to JSON and passed
          via -config flag. See the p3-controller source for options.
        '';
      };

      hap = {
        enable = mkEnableOption "HomeKit Switch accessory ('P3 Radio') over the brutella/hap library";

        pin = mkOption {
          type = types.strMatching "[0-9]{8}";
          example = "31415926";
          description = ''
            8-digit HomeKit pairing PIN. Apple rejects trivially weak
            pins (e.g. 12345678, all-same digits). Pick a random one
            and use it once when adding the accessory in iOS Home.
          '';
        };

        port = mkOption {
          type = types.port;
          default = 51834;
          description = ''
            TCP port the hap server listens on. Must not collide with
            other hap servers on the same host. Existing assignments
            on home.ldn at the time of writing: 51826 (nefit-homekit),
            51828 (tasmota-homekit), 51831 (z2m-homekit). Default
            51834 is the next free slot.
          '';
        };
      };
    };
  };

  config = mkMerge [
    (mkIf cfg.enable {
      # Sensible defaults; host configs can override via normal priority.
      services.owntone.settings = {
      general = {
        uid = mkDefault cfg.user;
        db_path = mkDefault "${cfg.dataDir}/songs3.db";
        cache_dir = mkDefault "${cfg.dataDir}/cache";
        logfile = mkDefault "/var/log/owntone.log";
        loglevel = mkDefault "log";
      };
      library = {
        name = mkDefault "OwnTone on %h";
        port = mkDefault 3689;
      };
    };

    users.users = mkIf (cfg.user == "owntone") {
      owntone = {
        isSystemUser = true;
        group = cfg.group;
        home = cfg.dataDir;
        extraGroups = ["audio"];
      };
    };

    users.groups = mkIf (cfg.group == "owntone") {
      owntone = {};
    };

    systemd.tmpfiles.rules =
      [
        "d ${cfg.dataDir} 0755 ${cfg.user} ${cfg.group} -"
        "d ${cfg.dataDir}/cache 0755 ${cfg.user} ${cfg.group} -"
        "f /var/log/owntone.log 0644 ${cfg.user} ${cfg.group} -"
      ]
      ++ lib.optionals (cfg.settings ? library && cfg.settings.library ? directories)
      (map (dir: "d ${dir} 0755 ${cfg.user} ${cfg.group} -") cfg.settings.library.directories);

    systemd.services.owntone = {
      description = "OwnTone DAAP/AirPlay media server";
      after = ["network-online.target" "avahi-daemon.socket"];
      requires = ["network.target" "local-fs.target" "avahi-daemon.socket"];
      wants = ["network-online.target"];
      wantedBy = ["multi-user.target"];

      restartTriggers = [configFile];

      startLimitBurst = 10;
      startLimitIntervalSec = 600;

      serviceConfig = {
        Type = "simple";
        ExecStart = "${getExe cfg.package} -f -c ${configFile}";
        User = cfg.user;
        Group = cfg.group;

        # Resource limits (from upstream systemd unit)
        MemoryMax = "256M";
        MemorySwapMax = "32M";

        # Restart policy
        Restart = "on-failure";
        RestartSec = 5;

        # Hardening
        NoNewPrivileges = true;
        ProtectSystem = "strict";
        ProtectHome = true;
        PrivateTmp = true;
        ReadWritePaths = [
          cfg.dataDir
          "/var/log"
        ];
      };
    };

    networking.firewall = mkIf cfg.openFirewall {
      allowedTCPPorts = [cfg.settings.library.port];
      allowedUDPPorts = [5353];
    };
  })

    (mkIf (cfg.enable && ccfg.enable) {
      # Controller defaults — owntone_url and listen derived from module config.
      services.owntone.controller.settings = {
        owntone_url = mkDefault "http://localhost:${toString cfg.settings.library.port}";
        listen = mkDefault ":${toString ccfg.port}";
        playlist_name = mkDefault "NRK P3";

        hap = mkIf ccfg.hap.enable {
          enabled = true;
          pin = ccfg.hap.pin;
          port = ccfg.hap.port;
          name = mkDefault "P3 Radio";
          # Resolved against StateDirectory below — hap subdir is
          # created by the binary on first run.
          state_dir = "/var/lib/p3-controller";
        };
      };

      systemd.services.p3-controller = let
        controllerConfigFile = controllerFormat.generate "p3-controller.json" ccfg.settings;
      in {
        description = "p3-controller — scheduled OwnTone playback";
        after = ["network.target" "owntone.service"];
        bindsTo = ["owntone.service"];
        wantedBy = ["multi-user.target"];

        restartTriggers = [controllerConfigFile];

        serviceConfig = {
          Type = "simple";
          ExecStart = "${getExe ccfg.package} -config ${controllerConfigFile}";
          DynamicUser = true;
          # /var/lib/p3-controller — survives upgrades, owned by the
          # DynamicUser. Holds HomeKit pairing state under hap/.
          StateDirectory = "p3-controller";
          StateDirectoryMode = "0700";
          Restart = "on-failure";
          RestartSec = 5;

          # Lifecycle: SIGTERM → main does ordered shutdown (hap mDNS
          # un-publish, ws close, http drain) within ~10s; KillMode=mixed
          # so any stragglers get SIGKILL via cgroup at TimeoutStopSec.
          KillMode = "mixed";
          TimeoutStopSec = "15s";

          # Hardening
          NoNewPrivileges = true;
          ProtectSystem = "strict";
          ProtectHome = true;
          PrivateTmp = true;
        };
      };

      networking.firewall = mkMerge [
        (mkIf ccfg.openFirewall {
          allowedTCPPorts = [ccfg.port];
        })
        (mkIf (ccfg.openFirewall && ccfg.hap.enable) {
          allowedTCPPorts = [ccfg.hap.port];
          allowedUDPPorts = [5353];
        })
      ];
    })
  ];
}
