---
{
  "kind": "pipeline",
  "name": "Kubernetes",
  "node_selector": { "drone": true },
  "platform": { "arch": "amd64", "os": "linux" },
  "steps":
    [
      {
        "commands":
          [
            "npm install prettier",
            "echo .pre-commit-config.yaml >> .prettierignore",
            'npx prettier --check "**/*.{ts,js,md,yaml,yml,sass,css,scss,html,htm}"',
          ],
        "image": "node:lts-buster",
        "name": "Prettier lint",
        "pull": "always",
      },
      {
        "commands":
          [
            "pwd",
            "echo $PATH",
            "apt update",
            "apt install -y git curl tar xz-utils apt-transport-https wget ninja-build gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip software-properties-common psmisc",
            "curl -sL https://deb.nodesource.com/setup_16.x | bash -",
            "curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -",
            'echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list',
            "apt update",
            "apt install -y nodejs yarn",
            "npm install --global zx",
            "add-apt-repository ppa:longsleep/golang-backports",
            "apt update",
            "apt install -y golang-go",
            "useradd -m ubuntu",
            "mkdir -p /home/ubuntu/git/dotfiles",
            "cp -r ./ /home/ubuntu/git/dotfiles/",
            "mkdir -p $HOME/local/nvim",
            "wget https://github.com/neovim/neovim/releases/download/v0.5.0/nvim-linux64.tar.gz -O nvim.tar.gz",
            "tar xzvf nvim.tar.gz --directory=$HOME/local/nvim --strip-components=1",
            'su "ubuntu"',
            "cd ~",
            "mkdir -p ~/.config",
            "mkdir -p $HOME/.local/share/nvim/lsp_servers/.zx",
            "cd $HOME/.local/share/nvim/lsp_servers/.zx; npm install zx; cd -",
            "cp -r ~/git/dotfiles/rcconfig/nvim ~/.config/nvim",
            '$HOME/local/nvim/bin/nvim --headless +"autocmd User PackerComplete sleep 100m | qall" +PackerSync',
            "sleep 30",
            '$HOME/local/nvim/bin/nvim --headless +"TSInstallSync maintained" +qa',
            '$HOME/local/nvim/bin/nvim +"LspInstall terraformls" &',
            "sleep 180",
            '$HOME/local/nvim/bin/nvim --headless +"TSInstallSync maintained" +qa',
            '$HOME/local/nvim/bin/nvim +"LspInstall terraformls" &',
            "sleep 180",
            '$HOME/local/nvim/bin/nvim --headless +"TSInstallSync maintained" +qa',
            '$HOME/local/nvim/bin/nvim +"LspInstall terraformls" &',
            "sleep 180",
            "mkdir -p $HOME/apps",
            "wget https://nightly.link/Kethku/neovide/workflows/build/main/neovide-windows.exe -O $HOME/apps/neovide.exe",
            "wget https://github.com/alacritty/alacritty/releases/download/v0.8.0/Alacritty-v0.8.0-portable.exe -O $HOME/apps/alacritty.exe",
            "mkdir -p /drone/src/dist",
            "tar -cJf /drone/src/dist/dotfiles.tar.xz git",
            "tar -cJf /drone/src/dist/nvim.tar.xz .config/nvim .local/share/nvim local/nvim",
            "tar -cJf /drone/src/dist/terminal.tar.xz apps",
          ],
        "environment":
          {
            "DEBIAN_FRONTEND": "noninteractive",
            "DISPLAY": ":9.0",
            "HOME": "/home/ubuntu",
          },
        "image": "ubuntu:latest",
        "name": "Build",
        "pull": "always",
      },
      {
        "environment": { "SSH_KEY": { "from_secret": "ssh_key" } },
        "image": "appleboy/drone-scp",
        "name": "Deploy with scp",
        "pull": "always",
        "settings":
          {
            "host": "core.terra.fap.no",
            "rm": true,
            "source": ["dist/*"],
            "strip_components": 1,
            "target": "/fastest/serve/builds/dotfiles",
            "username": "deploy",
          },
        "when": { "branch": ["master"], "event": ["push"] },
      },
      {
        "image": "appleboy/drone-discord",
        "name": "Notify Discord",
        "pull": "always",
        "settings":
          {
            "message": "{{#success build.status}}\n✅  Build #{{build.number}} of `{{repo.name}}` succeeded.\n\n📝  Commit by {{commit.author}} on `{{commit.branch}}`:\n``` {{commit.message}} ```\n🌐  {{ build.link }}\n\n✅  duration: {{duration build.started build.finished}}\n✅  started: {{datetime build.started \"2006/01/02 15:04\" \"UTC\"}}\n✅  finished: {{datetime build.finished \"2006/01/02 15:04\" \"UTC\"}}\n\n{{else}}\n@everyone\n❌  Build #{{build.number}} of `{{repo.name}}` failed.\n\n📝  Commit by {{commit.author}} on `{{commit.branch}}`:\n``` {{commit.message}} ```\n🌐  {{ build.link }}\n\n✅  duration: {{duration build.started build.finished}}\n✅  started: {{datetime build.started \"2006/01/02 15:04\" \"UTC\"}}\n✅  finished: {{datetime build.finished \"2006/01/02 15:04\" \"UTC\"}}\n\n{{/success}}\n",
            "webhook_id": { "from_secret": "discord_webhook_id" },
            "webhook_token": { "from_secret": "discord_webhook_token" },
          },
        "when":
          {
            "branch": ["master"],
            "event": ["push"],
            "status": ["success", "failure"],
          },
      },
    ],
  "type": "kubernetes",
}
