kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: if-not-exists
  image: ubuntu:latest
  commands:
    - apt update
    - apt install -y vim git
    - vim +PlugInstall +qall
    - ls
    - ls .vim
  when:
    branch:
    - master

      # - name: deploy
      #   pull: if-not-exists
      #   image: appleboy/drone-scp
      #   settings:
      #     host: storage.terra.fap.no
      #     rm: true
      #     source:
      #     - dist/*
      #     strip_components: 1
      #     target: /storage/nfs/k8s/builds/kubespace
      #     username: deploy
      #   environment:
      #     SSH_KEY:
      #       from_secret: ssh_key
      # 
      # - name: notify
      #   pull: if-not-exists
      #   image: drillster/drone-email
      #   settings:
      #     from: drone@drone.fap.no
      #     host: smtp.fap.no
      #     port: 25
      #     recipients:
      #     - kradalby@kradalby.no
      #     skip_verify: true
      #   when:
      #     status:
      #     - success
      #     - changed
      #     - failure
