cask_args appdir: '/Applications'
tap 'caskroom/cask'
tap 'caskroom/homebrew-versions'
tap 'grammarly/tap'
tap 'homebrew/bundle'
tap 'homebrew/games'
tap 'homebrew/devel-only'
cask 'java'

# Development

## Language/Runtimes
brew 'dmd'
brew 'erlang'
brew 'go'
brew 'node'
brew 'pypy'
brew 'pypy3'
brew 'python'
brew 'python3'
brew 'scala'
brew 'ocaml'


## Linting
brew 'flow'
brew 'tidy-html5'
brew 'swiftlint'
brew 'shellcheck'


## Tools
brew 'git'
brew 'git-lfs'
brew 'git-extras'
brew 'myrepos'
brew 'gradle'
brew 'maven'
brew 'kylef/formulae/swiftenv'
brew 'watchman'
brew 'fzf'
brew 'cloc'

## Libs
brew 'boost'
brew 'openssl'
brew 'jpeg'
brew 'libpng'
brew 'libtiff'

# Package manager
brew 'carthage'
brew 'rebar3'
brew 'opam'

# Shells
brew 'zsh'
brew 'fish'

# Command
brew 'xz'
brew 'pcre'
brew 'htop'
brew 'cowsay'
brew 'dos2unix'
brew 'figlet'
brew 'gnu-sed', args: ['with-default-names']
brew 'findutils', args: ['with-default-names']
brew 'coreutils'
brew 'jq'
brew 'ncdu'
brew 'gpg'
brew 'testssl'
brew 'supertux'
brew 'the_silver_searcher'
brew 'tmux'
brew 'tree'
brew 'unar'
brew 'unrar'
brew 'vim'
brew 'emacs', args: ['with-gnutls', 'with-imagemagick', 'with-cocoa', 'HEAD']
brew 'watch'
brew 'wget'
brew 'readline'

## Network
brew 'ipcalc'
brew 'wrk'
brew 'ptunnel'
brew 'nmap'
brew 'socat'
brew 'netcat'
brew 'netcat6'
brew 'syncthing'
brew 'syncthing-inotify'

## Database
brew 'sqlite'
brew 'postgresql'

brew 'caskroom/cask/brew-cask'
cask 'wireshark'
cask 'iterm2-beta'
cask 'tigervnc-viewer'
cask 'atom'
cask 'betterzipql'
cask 'cuda'
cask 'cuda-z'
cask 'firefox'
cask 'flux'
cask 'google-chrome'
cask 'intellij-idea'
cask 'pycharm'
cask 'clion'
cask 'microsoft-office'
cask 'mplayerx'
cask 'qlcolorcode'
cask 'qlimagesize'
cask 'qlmarkdown'
cask 'qlprettypatch'
cask 'qlstephen'
cask 'quicklook-csv'
cask 'quicklook-json'
cask 'skype'
cask 'spectacle'
cask 'spotify'
cask 'teamviewer'
cask 'transmission'
cask 'vlc'
cask 'webpquicklook'
cask 'jotta'
cask 'grammarly'
cask 'the-unarchiver'
cask 'discord'
cask 'sequel-pro'
cask 'nimble'
cask 'jumpcut'
cask 'messenger'
cask 'goofy'
cask 'chitchat'
cask 'calibre'
cask 'openra'
# cask 'qsyncthingtray'

cask 'osxfuse'
cask 'sshfs'
