#!/usr/bin/env bash
# -*- mode: shell-script -*-

set -euo pipefail

if [ $# -lt 1 ]; then
	echo "Usage: $0 host|all"
	exit 1
fi

onehost() {
	profile=${1//./-}
	shift
	# set -x
	# set +x

	host=${host//-/.}

	/run/current-system/sw/bin/rsync \
		--delete \
		--cvs-exclude \
		--exclude=result \
		--exclude=deploy \
		--exclude=.mypy_cache \
		--exclude=.pyre \
		-auv . "root@${host}:/etc/nixos"

	ssh -t "root@${host}" -- nixos-rebuild switch --flake "/etc/nixos#${profile}"
}

host=$1
shift
if [[ $host == "all" ]]; then
	for host in $(grep '= nixosBox' flake.nix | awk '{print $1}' | tr -d '"'); do
		echo
		echo "##################################"
		echo "# $host"
		echo "##################################"
		onehost "$host" "$@"
	done
else
	onehost "$host" "$@"
fi
