// Generated by Finicky Kickstart
// Save as ~/.finicky.js

module.exports = {
  defaultBrowser: "Google Chrome",
  handlers: [
    {
      match: /^https?:\/\/github\.com\/.*\/headscale\/.*$/,
      browser: "Safari"
    },
    {
      match: /^https?:\/\/youtube\.com\/.*$/,
      browser: "Firefox"
    },
    {
      match: /^https?:\/\/proton\.com\/.*$/,
      browser: "Safari"
    },
    {
      match: /^https?:\/\/proton\.me\/.*$/,
      browser: "Safari"
    }
  ]
}
