#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export LESS='-R -X -F'

export GOPATH=$HOME/go
export WORKON_HOME=$HOME/.virtualenvs
export PATH=$PATH:/usr/bin:/bin:/usr/sbin:/sbin:/usr/texbin:~/git/dotfiles/bin:$GOPATH/bin:~/bin
export LC_ALL=en_US.UTF-8  
export LANG=en_US.UTF-8
export TERM="xterm-256color"
export ANSIBLE_CONFIG=~/.ansible.cfg

if [[ "$OSTYPE" == darwin* ]];
then
    LESSPIPE=`which src-hilite-lesspipe.sh`
    export LESSOPEN="| ${LESSPIPE} %s"
    export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python
    export VIRTUALENVWRAPPER_VIRTUALENV=/usr/local/bin/virtualenv
    export VIRTUALENV_PYTHON=/usr/local/bin/python
    export ANSIBLE_HOSTS=~/.ansible_hosts
    export ANSIBLE_HOST_KEY_CHECKING=False
    export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home"
    export PATH=/usr/local/bin:$PATH
    export SPECIAL_PATH=/usr/local/opt/gnu-sed/libexec/gnubin

    export PATH=$SPECIAL_PATH:$PATH
fi



if [[ "$OSTYPE" == linux* ]];
then
    export LESSOPEN="| /usr/share/source-highlight/src-hilite-lesspipe.sh %s"
    export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python
    export VIRTUALENV_PYTHON=/usr/bin/python
    export JAVA_HOME=$(dirname $(dirname $(readlink -f  /usr/bin/java)))
fi
