#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

#Aliases
alias update_dotfiles="cd ~/git/dotfiles; git pull; cd -"
alias tb="nc termbin.com 9999"
alias cm="curl --silent http://whatthecommit.com/index.txt"


#Functions
push() {
    git add .
    git commit -m "$(cm)"
    git push origin $(git rev-parse --abbrev-ref HEAD)
}

if [[ "$OSTYPE" == darwin* ]];
then
    
    vnc () {
        re='^[0-9]+$'
        if [[ $1 =~ $re ]] ; then
            open vnc://localhost:$1
        else
            open vnc://$1:$2
        fi

    }

    socks () {
        help="Usage: eth or wlan, on or off"
        if [[ $1 =  "eth" ]]; then
            if [[ $2 = "on" ]]; then
                sudo networksetup -setsocksfirewallproxystate "Thunderbolt Ethernet" on
            elif [[ $2 = "off" ]]; then
                sudo networksetup -setsocksfirewallproxystate "Thunderbolt Ethernet" off
            else
                echo $help
            fi
        elif [[ $1 = "wlan" ]]; then    
            if [[ $2 = "on" ]]; then
                sudo networksetup -setsocksfirewallproxystate "Wi-Fi" on
            elif [[ $2 = "off" ]]; then
                sudo networksetup -setsocksfirewallproxystate "Wi-Fi" off
            else
                echo $help
            fi
        else
            echo $help
        fi
    }

fi

if [ -f /usr/local/bin/virtualenvwrapper.sh ];
then
    source /usr/local/bin/virtualenvwrapper.sh
fi

