alias ga 'git add'
alias gaa 'git add .'
# alias gc 'git commit'
# alias gcm 'git commit -m'
alias gco 'git checkout'
alias gcob 'git checkout -b'
alias gcom 'git checkout master'
alias gd 'git diff'
alias gb 'git branch'
alias gbd 'git branch -d '
alias gp 'git pull'
alias gss 'git status -s'
alias gst 'git stash'
alias gm 'git merge --no-ff'
alias gr 'git rebase'
alias grom 'git rebase origin/master'
alias grc 'git rebase --continue'
alias gra 'git rebase --abort'
alias gfo 'git fetch origin'
