alias k 'kubectl'
alias kg 'kubectl get'
alias kga 'kubectl get pods --all-namespaces'
alias kd 'kubectl describe'
alias ke 'kubectl edit'
alias kaf 'kubectl apply -f'
alias kdf 'kubectl delete -f'
alias kgc 'kubectl config get-contexts'
alias kshell 'kubectl run --generator=run-pod/v1 ubuntu-shell --rm -i --tty --image ubuntu -- bash'
alias kbusy 'kubectl run --generator=run-pod/v1 busybox-shell --rm -i --tty --image busybox -- sh'

alias kc 'set --universal -x KUBECONTEXT $argv[1]; kubectl config use-context'
