alias k 'kubectl'
alias kg 'kubectl get'
alias kga 'kubectl get pods --all-namespaces'
alias kd 'kubectl describe'
alias ke 'kubectl edit'
alias kaf 'kubectl apply -f'
alias kdf 'kubectl delete -f'
alias kshell 'kubectl run ubuntu-shell --rm -i --tty --image ubuntu -- bash'
