alias tf  "terraform"
alias tfi "terraform init"
alias tfiu "terraform init -upgrade"
alias tfp "terraform plan"
alias tfa "terraform apply"
alias tfaaa "terraform apply -auto-approve"
alias tft "terraform taint"
