#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export LESS='-R -X -F'

export GOPATH=$HOME/go
export PATH=$PATH:/usr/bin:/bin:/usr/sbin:/sbin:/usr/texbin:~/git/dotfiles/bin:$GOPATH/bin:~/bin
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export TERM="xterm-256color"
export ANSIBLE_CONFIG=~/.ansible.cfg

if [[ "$OSTYPE" == darwin* ]];
then
    LESSPIPE=`which src-hilite-lesspipe.sh`
    export LESSOPEN="| ${LESSPIPE} %s"
    export VIRTUALENV_PYTHON=/usr/local/bin/python
    export ANSIBLE_HOST_KEY_CHECKING=False
    export JAVA_HOME=`/usr/libexec/java_home`
    export CUDA_BIN="/Developer/NVIDIA/CUDA-7.5/bin"
    export HOMEBREW_PATH=/usr/local/bin
    export SED_PATH=/usr/local/opt/gnu-sed/bin
    export COREUTILS_PATH=/usr/local/opt/coreutils/libexec/gnubin
    export OVFTOOL_PATH=/Applications/VMware\ OVF\ Tool
    export SWIFTENV_ROOT=/usr/local/var/swiftenv
    export PATH=$HOMEBREW_PATH:$COREUTILS_PATH:$SED_PATH:$PATH:$OVFTOOL_PATH:$CUDA_BIN
fi



if [[ "$OSTYPE" == linux* ]];
then
    export LESSOPEN="| /usr/share/source-highlight/src-hilite-lesspipe.sh %s"
    export JAVA_HOME=$(dirname $(dirname $(readlink -f  /usr/bin/java)))
fi
