# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix
{
  pkgs,
  fetchurl,
  fetchgit,
  fetchhg,
}: self: super: {
  "Bootstrap-Flask" = super.buildPythonPackage rec {
    pname = "Bootstrap-Flask";
    version = "2.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/61/9f/7d4afab08e314e3ba7482d579140da50fe54119a623ad056e484c2067517/Bootstrap_Flask-2.0.0-py2.py3-none-any.whl";
      sha256 = "0m56yv0f56f6xmvg9zw1k12jkyfwmqvap5fy7hjli5i1vdyfm5x0";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."Flask"
      self."WTForms"
    ];
  };
  "Flask" = super.buildPythonPackage rec {
    pname = "Flask";
    version = "2.0.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8f/b6/b4fdcb6d01ee20f9cfe81dcf9d3cd6c2f874b996f186f1c0b898c4a59c04/Flask-2.0.2-py3-none-any.whl";
      sha256 = "0smbjcq74by9x8rhmqg1n8kahnwb909nc42j3xic8kcf3lpzd46b";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."Jinja2"
      self."Werkzeug"
      self."click"
      self."itsdangerous"
    ];
  };
  "Flask-Admin" = super.buildPythonPackage rec {
    pname = "Flask-Admin";
    version = "1.5.8";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/db/04/8a3fb1a40ff6752d644ddd76f517cc1c2caf246f7e4d0fb2515d462388db/Flask-Admin-1.5.8.tar.gz";
      sha256 = "0x7zg4k0ppw0n9j670iqmim0v6fixgx68p55agp1v24q3grs21pb";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."Flask"
      self."WTForms"
    ];
  };
  "Flask-Login" = super.buildPythonPackage rec {
    pname = "Flask-Login";
    version = "0.5.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2b/83/ac5bf3279f969704fc1e63f050c50e10985e50fd340e6069ec7e09df5442/Flask_Login-0.5.0-py2.py3-none-any.whl";
      sha256 = "187vyhwsppcpwmvqfi7hnkvzs9d43ckavbj5i6jpp0qp3q0balbl";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."Flask"
    ];
  };
  "Flask-Mail" = super.buildPythonPackage rec {
    pname = "Flask-Mail";
    version = "0.9.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/05/2f/6a545452040c2556559779db87148d2a85e78a26f90326647b51dc5e81e9/Flask-Mail-0.9.1.tar.gz";
      sha256 = "0hazjc351s3gfbhk975j8k65cg4gf31yq404yfy0gx0bjjdfpr92";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."Flask"
      self."blinker"
    ];
  };
  "Flask-Migrate" = super.buildPythonPackage rec {
    pname = "Flask-Migrate";
    version = "3.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a8/48/b64a6a2fee01b03f3318cba3aea1c0055ab5f4a933b2d4f5a2d75140c229/Flask_Migrate-3.1.0-py3-none-any.whl";
      sha256 = "15zqw8wrsg207v5a8hfagcq78v8nrzlqs1silbknpfhs4h38fjd6";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."Flask"
      self."Flask-SQLAlchemy"
      self."alembic"
    ];
  };
  "Flask-SQLAlchemy" = super.buildPythonPackage rec {
    pname = "Flask-SQLAlchemy";
    version = "2.5.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/26/2c/9088b6bd95bca539230bbe9ad446737ed391aab9a83aff403e18dded3e75/Flask_SQLAlchemy-2.5.1-py2.py3-none-any.whl";
      sha256 = "145kfksk7syc6bkwfl2xlhz8qwbiash7wlmr930xqzycqm63sb7i";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."Flask"
      self."SQLAlchemy"
    ];
  };
  "Flask-WTF" = super.buildPythonPackage rec {
    pname = "Flask-WTF";
    version = "1.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/5d/0a/59ddcce06b857a874187f2bc50da3fba8956c1855c19a2cc99d1dacab42a/Flask_WTF-1.0.0-py3-none-any.whl";
      sha256 = "15y7gs1fblqasmd0cniazp32qvkn1lzw4diziajcw1al77ycrzh1";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."Flask"
      self."WTForms"
      self."itsdangerous"
    ];
  };
  "Jinja2" = super.buildPythonPackage rec {
    pname = "Jinja2";
    version = "3.0.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/20/9a/e5d9ec41927401e41aea8af6d16e78b5e612bca4699d417f646a9610a076/Jinja2-3.0.3-py3-none-any.whl";
      sha256 = "1n0a775fml3fh1ph316j5dlqlcn81x5wmwfi8wxx0h3v9w0ycz07";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."MarkupSafe"
    ];
  };
  "Mako" = super.buildPythonPackage rec {
    pname = "Mako";
    version = "1.1.6";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b4/4d/e03d08f16ee10e688bde9016bc80af8b78c7f36a8b37c7194da48f72207e/Mako-1.1.6-py2.py3-none-any.whl";
      sha256 = "0mrs0igmlpqjxh33lwzky97n540w987b7f6pszx24nq7bm8qxbxg";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."MarkupSafe"
    ];
  };
  "MarkupSafe" = super.buildPythonPackage rec {
    pname = "MarkupSafe";
    version = "2.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/bf/10/ff66fea6d1788c458663a84d88787bae15d45daa16f6b3ef33322a51fc7e/MarkupSafe-2.0.1.tar.gz";
      sha256 = "02k2ynmqvvd0z0gakkf8s4idyb606r7zgga41jrkhqmigy06fk2r";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "PyJWT" = super.buildPythonPackage rec {
    pname = "PyJWT";
    version = "2.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2a/4d/67cc66a0c49003dc216fc73db2d05a3b80c7193167fd113da1f2c678ac2a/PyJWT-2.3.0-py3-none-any.whl";
      sha256 = "0brj319ypgm0yzr7fa4kaqyx05wn60v50k7cn7swgw0aky6vpi70";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "SQLAlchemy" = super.buildPythonPackage rec {
    pname = "SQLAlchemy";
    version = "1.4.29";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/80/7c/ab3470159bab67fcb28bc4038c55751d6b333a59b70af8943a95e470f8ab/SQLAlchemy-1.4.29.tar.gz";
      sha256 = "0f8b0bwkxs88zsxldwvpjvkx6pcixk9c2sf9rx4scjs7w4aasazs";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."greenlet"
    ];
  };
  "WTForms" = super.buildPythonPackage rec {
    pname = "WTForms";
    version = "3.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/eb/2e/199a0edf6577af771a68fbd950d98f0c1a16bb5fa956e45772005318c702/WTForms-3.0.1-py3-none-any.whl";
      sha256 = "0jw39c9d03l9kj9izbyslavp4kms9s8jp5l452wq35571h72yzw3";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."MarkupSafe"
    ];
  };
  "Werkzeug" = super.buildPythonPackage rec {
    pname = "Werkzeug";
    version = "2.0.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1e/73/51137805d1b8d97367a8a77cae4a792af14bb7ce58fbd071af294c740cf0/Werkzeug-2.0.2-py3-none-any.whl";
      sha256 = "13yyk5l09mlkv7pwmbv5sxskna4pfcgqdabzx4spwyqfyqfdrlv3";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "alembic" = super.buildPythonPackage rec {
    pname = "alembic";
    version = "1.7.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/61/e1/5b00232d840276df2be60f3d6262019198070a47e971f9bc772612f9ce59/alembic-1.7.5-py3-none-any.whl";
      sha256 = "1d4qw1x7f2zncvhr65xw4wg58lr95ak8wkk4v5rpagafad0ykpd9";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."Mako"
      self."SQLAlchemy"
    ];
  };
  "blinker" = super.buildPythonPackage rec {
    pname = "blinker";
    version = "1.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1b/51/e2a9f3b757eb802f61dc1f2b09c8c99f6eb01cf06416c0671253536517b6/blinker-1.4.tar.gz";
      sha256 = "1dpq0vb01p36jjwbhhd08ylvrnyvcc82yxx3mwjx6awrycjyw6j7";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "click" = super.buildPythonPackage rec {
    pname = "click";
    version = "8.0.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/48/58/c8aa6a8e62cc75f39fee1092c45d6b6ba684122697d7ce7d53f64f98a129/click-8.0.3-py3-none-any.whl";
      sha256 = "1wwfa6j4490kd2qawk68a4ikf8nbj6gjynazdc5v9bmdjmj4cgrm";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "dnspython" = super.buildPythonPackage rec {
    pname = "dnspython";
    version = "2.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f5/2d/ae9e172b4e5e72fa4b3cfc2517f38b602cc9ba31355f9669c502b4e9c458/dnspython-2.1.0-py3-none-any.whl";
      sha256 = "05jj2cwsc9igyic42iw7h3mwgzjzqsm4kz56l791hw9iy1p2zlcm";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "email-validator" = super.buildPythonPackage rec {
    pname = "email-validator";
    version = "1.1.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9e/e4/e01e92092fdac940f10fa4c8ac3481bf70fc74023a76f5c72020c9445e68/email_validator-1.1.3-py2.py3-none-any.whl";
      sha256 = "02s4v2avszpqlj18dyic4wzvymk70myab6161vj3fshhnz7chxan";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."dnspython"
      self."idna"
    ];
  };
  "greenlet" = super.buildPythonPackage rec {
    pname = "greenlet";
    version = "1.1.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/0c/10/754e21b5bea89d0e73f99d60c83754df7cc64db74f47d98ab187669ce341/greenlet-1.1.2.tar.gz";
      sha256 = "0jkln5bf6rq7dbvpv7ypin3pp9jqd2jr91yyxlnfcii3msj5w3z3";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "idna" = super.buildPythonPackage rec {
    pname = "idna";
    version = "3.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/04/a2/d918dcd22354d8958fe113e1a3630137e0fc8b44859ade3063982eacd2a4/idna-3.3-py3-none-any.whl";
      sha256 = "1zrm4xnjas13byafi11ma2q8h5rr1fmjwvi41xp5k07sgw2dvnc4";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "itsdangerous" = super.buildPythonPackage rec {
    pname = "itsdangerous";
    version = "2.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9c/96/26f935afba9cd6140216da5add223a0c465b99d0f112b68a4ca426441019/itsdangerous-2.0.1-py3-none-any.whl";
      sha256 = "0z7952x119yy003bjgdsjb81nici0dq2jc0shkdjnr9pjr5hjx2i";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "python-dotenv" = super.buildPythonPackage rec {
    pname = "python-dotenv";
    version = "0.19.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/0e/f1/0317f4b2c5284075a2154fe95539b43c0acecbcb86fe80fcb2645803edd9/python_dotenv-0.19.2-py2.py3-none-any.whl";
      sha256 = "1lxif64lq3072s2z7w985z3c6lq07nw6s76s8v1s7lrzhz0vvcij";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
}
